format = "$directory$all"

[kubernetes]
disabled = false
format = '\([$symbol](bold fg:33)[$cluster](fg:166):[$namespace](dimmed green)\) '
symbol = "☸"

[aws]
disabled = false
symbol = "☁️ "
force_display = true
style = "yellow"

[python]
disabled = true

[battery]
disabled = false

[lua]
disabled = false

[directory]
truncation_length = 8
truncation_symbol = "…/"

[cmd_duration]
min_time = 2000
