format = "$directory$all"

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[kubernetes]
disabled = false
format = '\([⎈](bold fg:33) [$cluster](fg:166):[$namespace](dimmed green)\) '

[aws]
disabled = false
force_display = true
style = 'yellow'

[python]
disabled = false

[battery]
disabled = false
