format = "$directory$all"

[kubernetes]
disabled = false
format = '\([âŽˆ](bold fg:33) [$cluster](fg:166):[$namespace](dimmed green)\) '

[aws]
disabled = false

[python]
disabled = true

[battery]
disabled = false
