---
name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  # pull_request: null

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Copy configs to root
        run: |
          mkdir -p .github/linters
          for file_n in .editorconfig .shellcheckrc .prettierignore zizmor.yaml selene.toml vim.toml .luacheckrc; do
            echo "Copying $file_n"
            cp nvim/"$file_n" "$file_n"
            cp nvim/"$file_n" ".github/linters/${file_n}"
          done

      - name: Super-linter
        uses: super-linter/super-linter/slim@v8.3.2 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # VALIDATE_ALL_CODEBASE: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_JSCPD: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_JUPYTER_NBQA_RUFF: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_RUFF_FORMAT: false
          VALIDATE_SHELL_SHFMT: false # because zsh files fail this test.
